---
name: deploy-docs
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
      # - entelecheia/*
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - "book/**"
      - "src/os2024/book/**"
      - ".github/workflows/deploy-docs.yaml"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # install the source code
      - name: Install the source code
        run: pip install .

      # Build the book
      - name: Build the book
        run: |
          pip install -r book/requirements.txt
          jupyter-book build book

      # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/_build/html
          cname: os2024.halla.ai
